version: 2

sources:
  - name: SNOWFLAKE_SAMPLE_DATA
    description: 'A sample datbase provided by Snowflake'
    database: snowflake_sample_data
    schema: TPCDS_SF10TCL
    tables:
      - name: store_sales
        description: 'Details about sales in stores.'
        # - columns : ...

models:
  - name: snowflake_sample_data__store_sales
    description: "Sales from stores"
    # columns:
      # - name: id
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null