version: 2

sources:
  - name: SNOWFLAKE_SAMPLE_DATA
    description: 'A sample datbase provided by Snowflake'
    database: snowflake_sample_data
    schema: TPCDS_SF10TCL
    tables:
      - name: store_sales
        description: 'Details about sales in stores.'
        # - columns : ...